# This values were obtained by writing down 3 points in the curve
#   rad    |   msr
# ---------+--------
#    0     |   530
# 1.5707   |   180
# -1.5707  |   900
#          |
#
# Then, fitting a 2nd order polynomial on wolfram alpha as:
# https://www.wolframalpha.com/input/?i=fit+((530,0),(900,-1.5707),(180,1.5707))
#
# This gives a linear correlation of:
# 0.00402391*P - 2.03342
#
copter_arm:
  gain: 0.00436193
  bias: -2.3409
